import type { Metadata } from "next";
import "./globals.css";
import { HeaderNav } from "@/components/header-nav/HeaderNav";
import { FooterNav } from "@/components/footer-nav/FooterNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`overflow-hidden antialiased h-screen min-h-screen  w-screen flex justify-between flex-col items-center`}
      >
        <HeaderNav />
        {children}
        <FooterNav />
      </body>
    </html>
  );
}
